apiVersion: skaffold/v3
kind: Config
metadata:
  name: file-server
build:
  artifacts:
    - image: kazirashid/file-server
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
manifests:
  kustomize:
    paths:
      - k8s\base
profiles:
  - name: development
    manifests:
      kustomize:
        paths:
          - k8s\overlays\development
