---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: files
spec:
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/files
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files
spec:
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          image: kazirashid/file-server:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 256m
              memory: 256Mi
            limits:
              cpu: 512m
              memory: 512Mi
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api
spec:
  minReplicas: 1
  maxReplicas: 3
