apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./../../base

patchesStrategicMerge:
  - mongodb.yaml
  - redis.yaml
  - api.yaml

secretGenerator:
  - name: mongodb
    type: Opaque
    behavior: merge
    literals:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=secret
