---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 0Mi
  hostPath:
    path: /data/storage
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0Mi
  volumeName: storage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  serviceName: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: kazirashid/file-server:latest
          imagePullPolicy: Always
          env:
            - name: RATE_LIMIT_PROVIDER
              value: redis
            - name: REDIS_URI
              value: redis://redis:6379
            - name: DB_PROVIDER
              value: mongodb
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_PASSWORD
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb
                  key: MONGODB_DATABASE
            - name: MONGODB_URI
              value: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}
            - name: STORAGE_TEMP_LOCATION
              value: '.tmp'
            - name: STORAGE_PROVIDER
              value: local
            - name: LOCAL_STORAGE_LOCATION
              value: '_storage'
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3002"
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 0m
              memory: 0Mi
          ports:
            - containerPort: 3002
          volumeMounts:
            - name: storage
              mountPath: '_storage'
            - name: temp
              mountPath: '.tmp'
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage
        - name: temp
          emptyDir: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api
  labels:
    app: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: api
    kind: StatefulSet
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  minReplicas: 0
  maxReplicas: 0
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3002
      nodePort: 30101
