---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 0Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0Mi
  volumeName: mongodb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb
  labels:
    app: mongodb
data:
  MONGODB_DATABASE: file_share
  init-mongodb.js: |
    db.createUser({
      user: 'admin',
      pwd: 'secret',
      roles: ['dbOwner']
    });
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0.2-focal
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb
                  key: MONGODB_DATABASE
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 0m
              memory: 0Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
            - name: mongodb
              mountPath: /data/db
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb
        - name: init-script
          configMap:
            name: mongodb
            items:
              - key: init-mongodb.js
                path: init-mongodb.js
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: mongodb
    kind: StatefulSet
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  minReplicas: 0
  maxReplicas: 0
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
