name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Release
        run: |
          npm ci
          npm run release
      - name: Upload coverage
        uses: codecov/codecov-action@v2
