name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run format && npm run lint && npm run compile
      - name: Test
        run: npm run coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Image Meta
        id: image-meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short,prefix=
          images: ${{ secrets.DOCKERHUB_USERNAME }}/file-server
      - name: Push Image
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.image-meta.outputs.tags }}
          labels: ${{ steps.image-meta.outputs.labels }}
